### ISSUE TITLE
제목 내용이 공격적이라는 피드백을 받았습니다

### ISSUE THREAD

**Issue by syriahamster** [syriahamster/time-game#13]
"한국인 상식수준 측정기" 라는 제목이 공격적이라는 피드백을 받았습니다.
좀 더 순화한 형태의 제목 선발이 필요할 것 같습니다

**Comment by brightscannon** [comment]
수준이라는 말을 빼야할듯.

나의 상식레벨은?? 은 어떤가

**Comment by syriahamster** [comment]
상식 이라는 단어 자체가 남에게 사용할 때
"너 상식이란게 있냐?"
라고 보통 사용되므로 첫 이미지에 그닥 좋지 않은 것 같음
우선 담백하게 연도 맞추기라고 하면 좋을듯

**Comment by syriahamster** [comment]
변경완료
