### ISSUE TITLE
깜빡임 문제

### ISSUE THREAD

**Issue by syriahamster** [syriahamster/time-game#27]
문제 페이지 갱신시 페이지가 정렬되는 것으로 보이는 깜빡임이 존재합니다 (모바일)

**Comment by syriahamster** [comment]
반영하습니다.
그러나 페이지 갱신시 문제가 변경되는 깜빡임 현상은 여전합니다.

**Comment by brightscannon** [comment]
해결하였음 

onMount에 추가하여 해결
