### ISSUE TITLE
난이도 수정필요

### ISSUE THREAD

**Issue by syriahamster** [syriahamster/time-game#28]
![Screenshot_20221126-093134_Chrome](https://user-images.githubusercontent.com/76864738/204066205-e09c3fdf-b2ad-4d7c-9c6a-98e1abd58630.jpg)

22개 문제를 풀었으나 겨우 4점밖에 얻지 못했습니다
문제를 풀고난 뒤 기분이 별로 좋지 않습니다

**Comment by syriahamster** [comment]
격차가 5년내인 경우 1점
격차가 3년내인 경우 2점
완전 일치한 경우 3점
으로 스코어를 얻도록 수정

**Comment by brightscannon** [comment]
로직은 수정함
